[build]
base = "react-app/"
command = "npm run build"
publish = "build/"

[context.production]
# environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "https://mobile.guvenlibtc.com/api/:splat"

[[redirects]]
force = true
from = "/socket/*"
status = 200
to = "https://35.180.109.191/:splat"

[[redirects]]
force = true
from = "/socket.io/*"
status = 200
to = "https://35.180.109.191/:splat"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
