name: Node CI

on:
  push:
    branches: [react]
  pull_request:
    branches: [react]
    types: [opened, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: react
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: install & build
        run: |
          cd react-app
          yarn
          NODE_ENV=production yarn build
        env:
          # NODE_ENV: production
          SKIP_PREFLIGHT_CHECK: true
